[[headers]]
for = "/*"
  [headers.values]
  Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' https://jsisjfkucnluxaaxraxt.supabase.co; style-src 'self' 'unsafe-inline'; img-src 'self' data: https://*.supabase.co; font-src 'self' data:; connect-src 'self' 'unsafe-inline' https://*.supabase.co wss://*.supabase.co; frame-src 'self' 'unsafe-inline' https://yandex.ru"